// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Alif.Core.Entities
{
    public  class Shelter : BaseEntity
    {
        
        public string SEmail { get; set; }       
        public string SLocation { get; set; }    
        public string ManagerPhone { get; set; }      
        public int AvailablePlaces { get; set; }
        public string SName { get; set; }
        [DataType(DataType.ImageUrl)]
        public string? Image { get; set; }
        public string AppUserId { get; set; }
        public ApplicationUser user { get; set; }

    }
}